version: 0.2

env:
  shell: bash
  
phases:
  install:
    commands:
      - apt-get install zip -y
      - apt-get install jq -y
      #- curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #- unzip awscliv2.zip
      #- ./aws/install
      - ls -lrt
      - aws sts get-caller-identity
      - aws --version
      - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - aws-iam-authenticator help
      - curl -o /opt/kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.7/2020-07-08/bin/linux/amd64/kubectl
      - chmod +x /opt/kubectl
      - mv /opt/kubectl /usr/bin
      - cp kubeconfig /opt/kubeconfig
      - export KUBECONFIG=/opt/kubeconfig
      
        
  build:
    commands:
      - kubectl get svc 
      - kubectl apply -f nginx.yaml
