version: 0.2

env:
  shell: bash
  
phases:
  install:
    commands:
      - apt-get install zip -y
      - apt-get install jq -y
#       - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
#       - unzip awscliv2.zip
#       - ./aws/install
      - ls -lrt
      - aws sts get-caller-identity
      - aws --version
      - curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p $HOME/bin && cp ./aws-iam-authenticator $HOME/bin/aws-iam-authenticator && export PATH=$PATH:$HOME/bin
      - echo 'export PATH=$PATH:$HOME/bin' >> ~/.bashrc
      - aws-iam-authenticator help
      - curl -o /opt/kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.17.7/2020-07-08/bin/linux/amd64/kubectl
      - chmod +x /opt/kubectl
      - mv /opt/kubectl /usr/bin
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      
  pre_build: # Add kubeconfig to access to EKS cluster
    commands:
      - aws eks --region ap-southeast-1 update-kubeconfig --name wordpress-eks-cluster
      
  build:
    commands:
      - cd docker
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 739521814962.dkr.ecr.ap-southeast-1.amazonaws.com
      - docker build -t web-application:$IMAGE_VERSION .
      - docker tag web-application:$IMAGE_VERSION 739521814962.dkr.ecr.ap-southeast-1.amazonaws.com/web-application:$IMAGE_VERSION
      - docker push 739521814962.dkr.ecr.ap-southeast-1.amazonaws.com/web-application:$IMAGE_VERSION
      - cd ..

  post_build: # kubernetes deployment
    commands:
      - cat ~/.kube/config
      - kubectl get svc --namespace kube-system
      - "helm upgrade -i web-app ./web-app -f web-app/values.yaml --set image.repository=$IMAGE_REPO_URL --set image.tag=$IMAGE_VERSION --set replicaCount=4"
